/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Assistant;

import com.crsystem.systemclient.controller.TimetableController;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author wonsik
 */
public class RoomModifyGUI extends javax.swing.JPanel {

    private String roomName;
    private Runnable onSaved;

    public RoomModifyGUI(String roomName, Map<String, Object> roomInfo, Runnable onSaved) {
        this.roomName = roomName;
        this.onSaved  = onSaved;
        initComponents();
        populateFields(roomInfo);
        
        int cap = (int) roomInfo.getOrDefault("capacity", 0);
        int comp = (int) roomInfo.getOrDefault("computerCount", 0);
    
        jSpinnerMaxCap.setModel(new javax.swing.SpinnerNumberModel(cap, 0, 60, 1));
        jSpinnerComputerCnt.setModel(new javax.swing.SpinnerNumberModel(comp, 0, 60, 1));
        
        jButton1.addActionListener(e -> handleSave());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMaxCap = new javax.swing.JLabel();
        jSpinnerMaxCap = new javax.swing.JSpinner();
        jSpinnerComputerCnt = new javax.swing.JSpinner();
        jLabelComputerCnt = new javax.swing.JLabel();
        jLabelUseable = new javax.swing.JLabel();
        jRadioButtonUseable = new javax.swing.JRadioButton();
        jRadioButtonUnusable = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelFeature = new javax.swing.JLabel();
        jTextFieldFeature = new javax.swing.JTextField();

        jLabelMaxCap.setText("최대 수용 인원");

        jLabelComputerCnt.setText("컴퓨터 개수");

        jLabelUseable.setText("사용 가능 여부");

        jRadioButtonUseable.setText("사용 가능");

        jRadioButtonUnusable.setText("사용 불가");

        jTextField1.setText("최대 수용 인원, 컴퓨터 개수 60");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUseable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonUseable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonUnusable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMaxCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinnerMaxCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelComputerCnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerComputerCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxCap)
                    .addComponent(jSpinnerMaxCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComputerCnt)
                    .addComponent(jSpinnerComputerCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUseable)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonUseable)
                        .addComponent(jRadioButtonUnusable)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setText("수정하기");

        jLabelFeature.setText("특이사항");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFeature)
                            .addComponent(jTextFieldFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFeature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    @SuppressWarnings("unchecked")
    private void populateFields(Map<String, Object> info) {
        if (info == null) return;
        Object cap = info.get("capacity");
        if (cap instanceof Integer) jSpinnerMaxCap.setValue(cap);
        Object cnt = info.get("computerCount");
        if (cnt instanceof Integer) jSpinnerComputerCnt.setValue(cnt);
        String status = (String) info.get("status");
        if ("사용 불가".equals(status)) {
            jRadioButtonUnusable.setSelected(true);
        } else {
            jRadioButtonUseable.setSelected(true);
        }
        String features = (String) info.get("features");
        jTextFieldFeature.setText(features != null ? features : "");
    }

    private void handleSave() {
        int capacity = (int) jSpinnerMaxCap.getValue();
    int computerCount = (int) jSpinnerComputerCnt.getValue();
    
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("roomName",      roomName);
        payload.put("capacity",      (int) jSpinnerMaxCap.getValue());
        payload.put("computerCount", (int) jSpinnerComputerCnt.getValue());
        payload.put("status",        jRadioButtonUseable.isSelected() ? "사용 가능" : "사용 불가");
        payload.put("features",      jTextFieldFeature.getText().trim());

        jButton1.setEnabled(false);
        TimetableController.getInstance().updateRoomInfo(payload,
            response -> {
                jButton1.setEnabled(true);
                if (response.isSuccess()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "수정이 완료되었습니다.");
                    if (onSaved != null) onSaved.run();
                    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "수정 실패: " + response.getMessage());
                }
            },
            error -> {
                jButton1.setEnabled(true);
                javax.swing.JOptionPane.showMessageDialog(this, "통신 오류: " + error);
            }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelComputerCnt;
    private javax.swing.JLabel jLabelFeature;
    private javax.swing.JLabel jLabelMaxCap;
    private javax.swing.JLabel jLabelUseable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonUnusable;
    private javax.swing.JRadioButton jRadioButtonUseable;
    private javax.swing.JSpinner jSpinnerComputerCnt;
    private javax.swing.JSpinner jSpinnerMaxCap;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFeature;
    // End of variables declaration//GEN-END:variables
}
