/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.crsystem.systemclient.view;

import com.crsystem.common.model.ReservationInfo;

/**
 *
 * @author abalo
 */
public class CRSystemReservation extends javax.swing.JFrame {

    public static java.util.List<ReservationInfo> reservationList = new java.util.ArrayList<>();
    private java.util.List<java.time.LocalDate> dateValues = new java.util.ArrayList<>();

    private String day;
    private String periodInfo;
    private int duration;
    private String roomName;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CRSystemReservation.class.getName());

    /**
     * Creates new form CRSystemReservation
     */
    public CRSystemReservation(String roomName, String day, String periodInfo, int duration) {
        this.roomName = roomName;
        this.day = day;
        this.periodInfo = periodInfo;
        this.duration = duration;

        initComponents();
        customInit(); // 날짜 세팅 등을 위한 추가 메서드 호출
    }

    private void customInit() {
        lblInfo.setText("[" + roomName + "] " + day + "요일 / " + periodInfo);

        // 오늘 기준 -14일 ~ +14일 날짜 생성
        java.time.LocalDate today = java.time.LocalDate.now();
        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();

        for (int i = -14; i <= 14; i++) {
            java.time.LocalDate d = today.plusDays(i);
            String label = d.toString() + " (" + dayNames[d.getDayOfWeek().getValue()] + ")";
            model.addElement(label);
            dateValues.add(d); // 실제 LocalDate 값 저장
        }

        dateCombo.setModel(model);
        dateCombo.setSelectedIndex(14); // 오늘 날짜 선택

        // 사용자 구분 세팅
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"학생", "교수"}));

        // 창을 닫아도 프로그램 전체가 꺼지지 않게 설정
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox<>();
        typeCombo = new javax.swing.JComboBox<>();
        purposeField = new javax.swing.JTextField();
        partnerSpinner = new javax.swing.JSpinner();
        btnList = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInfo.setText("jLabel1");

        jLabel2.setText("날짜 선택 :");

        dateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        purposeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        purposeField.addActionListener(this::purposeFieldActionPerformed);

        btnList.setText("예약 목록 확인");
        btnList.addActionListener(this::btnListActionPerformed);

        btnSubmit.setText("예약 등록");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        jLabel3.setText("사용자 선택(테스트용) :");

        jLabel4.setText("사용 목적 : ");

        jLabel5.setText("동반 인원 수 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(partnerSpinner)
                        .addComponent(purposeField)
                        .addComponent(typeCombo, 0, 201, Short.MAX_VALUE)
                        .addComponent(dateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purposeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        java.time.LocalDate selectedDate = dateValues.get(dateCombo.getSelectedIndex());
        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        String actualDay = dayNames[selectedDate.getDayOfWeek().getValue()];

        // 1. 요일 매칭 검증 (시간표 요일과 선택 날짜 요일 대조)
        if (!actualDay.equals(this.day)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "선택하신 날짜는 " + actualDay + "요일입니다.\n시간표에서 선택한 " + this.day + "요일과 일치해야 합니다.");
            return;
        }

        String type = (String) typeCombo.getSelectedItem();
        // 신분별 예약 가능 시간 체크
        if ("학생".equals(type) && duration > 2) {
            javax.swing.JOptionPane.showMessageDialog(this, "학생은 최대 2교시까지만 예약 가능합니다.");
            return;
        }
        if ("교수".equals(type) && duration > 3) {
            javax.swing.JOptionPane.showMessageDialog(this, "교수는 최대 3교시까지만 예약 가능합니다.");
            return;
        }

        // 예약 정보 저장
        ReservationInfo info = new ReservationInfo();
        info.roomName = this.roomName;
        info.date = selectedDate;
        info.day = this.day;
        info.periodInfo = this.periodInfo;
        info.userType = type;
        info.purpose = purposeField.getText();
        info.partnerCount = (int) partnerSpinner.getValue();
        info.status = "교수".equals(type) ? "예약 확정" : "대기 중";

        reservationList.add(info);
        javax.swing.JOptionPane.showMessageDialog(this, "예약 성공! 상태: " + info.status);
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        new ReservationListUI().setVisible(true);
    }//GEN-LAST:event_btnListActionPerformed

    private void purposeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CRSystemReservation("23 정보공학관 9층 912호", "월", "1교시", 1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JSpinner partnerSpinner;
    private javax.swing.JTextField purposeField;
    private javax.swing.JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
