/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.crsystem.systemclient.view;

import com.crsystem.common.dto.RequestDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.systemclient.main.CRSystemClient;
import com.crsystem.common.dto.UserDTO;
import com.crsystem.common.enums.*;
import com.crsystem.systemclient.controller.UserController;
import com.crsystem.systemclient.view.Admin.AdminGUI;
import com.crsystem.systemclient.view.Assistant.AssistantGUI;

// import javax.swing.ButtonModel;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;



/**
 *
 * @author wonsik
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());
    
    
    // 테스트를 위해 주석 처리 
    // private javax.swing.ButtonGroup roleGroup;
    
    /**
     * 실행 시 LoginGUI 기본 설정
     */
    public LoginGUI() {
        initComponents();
        jTextFieldID.requestFocusInWindow();    // 초기화 시 ID field에 포커싱
        
        // btn 설정 
        initRoleRadioButtons();
        
        // 초기 사이즈 설정
        this.setSize(550, 350);
        // 창 크기 변경 불가 
        this.setResizable(false);
        // 화면 모니터 중앙 배치
        this.setLocationRelativeTo(null);
        
        // 시계 생성
        jLabelTime.setText(getTime());
        new javax.swing.Timer(1000, e -> {
            jLabelTime.setText(getTime()); 
        }).start();
    }
    
    // button 값 지정 
    private void initRoleRadioButtons() {

        buttonGroupRole.add(jRadioButtonAdm);
        buttonGroupRole.add(jRadioButtonAss);
        buttonGroupRole.add(jRadioButtonPro);
        buttonGroupRole.add(jRadioButtonStu);
        
        // 식별자(ActionCommand) 심기
        jRadioButtonAdm.setActionCommand(Role.ADMIN.name());
        jRadioButtonAss.setActionCommand(Role.ASSISTANT.name());
        jRadioButtonPro.setActionCommand(Role.PROFESSOR.name());
        jRadioButtonStu.setActionCommand(Role.STUDENT.name());
        
       
    }
       
    // 로그인 실패 시 비밀번호 란 초기화
    public void resetFieldsForFailure() {
        jPasswordField1.setText("");
        jTextFieldID.requestFocusInWindow();
    }
    
    // 현재 시간을 가져와서 ISO 8601 형태로 설정
    private String getTime() {
        return java.time.LocalDateTime.now()
                        .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'    'HH:mm:ss"));
    }
    
    // Getter
    public String getEnteredId() {
        return jTextFieldID.getText();
    }
    public String getEnteredPassword() {
        return new String(jPasswordField1.getPassword());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRole = new javax.swing.ButtonGroup();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelDetail = new javax.swing.JPanel();
        jTextFieldID = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jRadioButtonAss = new javax.swing.JRadioButton();
        jRadioButtonPro = new javax.swing.JRadioButton();
        jRadioButtonStu = new javax.swing.JRadioButton();
        jLabelTime = new javax.swing.JLabel();
        jRadioButtonAdm = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitle.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabelTitle.setText("<html><center> Class-Room Reservation <br>SYSTEM </center></html>");
        jPanelTitle.add(jLabelTitle, new java.awt.GridBagConstraints());

        jTextFieldID.setText("ID");

        jPasswordField1.setText("jPasswordField1");

        jButtonLogin.setText("Login");
        jButtonLogin.setActionCommand("jButtonLogin");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jRadioButtonAss.setText("조교");

        jRadioButtonPro.setText("교수");

        jRadioButtonStu.setText("학생");

        jLabelTime.setText("Current Time");

        jRadioButtonAdm.setText("관리자");

        javax.swing.GroupLayout jPanelDetailLayout = new javax.swing.GroupLayout(jPanelDetail);
        jPanelDetail.setLayout(jPanelDetailLayout);
        jPanelDetailLayout.setHorizontalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTime)
                            .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField1)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogin))
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonStu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDetailLayout.setVerticalGroup(
            jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAss)
                    .addComponent(jRadioButtonPro)
                    .addComponent(jRadioButtonStu)
                    .addComponent(jRadioButtonAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDetailLayout.createSequentialGroup()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabelTime))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        
        String id = getEnteredId().trim();
        String pw = getEnteredPassword().trim();

        if (id.isEmpty() || pw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디 또는 비밀번호를 입력해주세요.");
            return; 
        }

        if (buttonGroupRole.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "사용자 권한을 선택해주세요.");
            return;
        }
        
        // 입력받은 권한 및 데이터 준비
        String roleString = buttonGroupRole.getSelection().getActionCommand();
        Role selectedRole = Role.valueOf(roleString);
        
        if (selectedRole == Role.PROFESSOR || selectedRole == Role.ASSISTANT) {
            if (!id.matches("^\\d{5}$")) {
                JOptionPane.showMessageDialog(this, "교수 및 조교의 ID는 5자리 숫자여야 합니다.", "형식 오류", JOptionPane.WARNING_MESSAGE);
                return; // 형식에 맞지 않으면 서버로 보내지 않고 바로 종료
            }
        } else if (selectedRole == Role.STUDENT) {
            if (!id.matches("^\\d{8}$")) {
                JOptionPane.showMessageDialog(this, "학생의 ID는 8자리 숫자여야 합니다.", "형식 오류", JOptionPane.WARNING_MESSAGE);
                return; 
            }
        }
        
        UserController.getInstance().login(
            id, 
            pw, 
            selectedRole, 
            (ResponseDTO response) -> {
                // --- 통신 성공 시 (서버 응답 도착) ---
                if (response.isSuccess()) {
                    // 성공 시 사용자 정보 추출
                    UserDTO.Response userInfo = (UserDTO.Response) response.getPayload();
                    
                    // 권한 검사 필요시 작성 
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "로그인 성공! 환영합니다, " + userInfo.getName() + "님");
                        
                        Role displayRole = userInfo.getRole();
                        
                        // 실제 계정은 조교인데 교직원(교수)을 선택해 성공했다면 교수 화면으로 우회
                        if (userInfo.getRole() == Role.ASSISTANT && selectedRole == Role.PROFESSOR) {
                            displayRole = Role.PROFESSOR;
                        }
                        
                        // 권한별 GUI 분기 
                        switch (displayRole) {
                            case STUDENT:
                                // new StudentGUI().setVisible(true);
                                break;
                            case PROFESSOR:
                                // new ProfessorGUI().setVisible(true);
                                break;
                            case ASSISTANT:
                                new AssistantGUI(userInfo).setVisible(true);
                                break;
                            case ADMIN:
                                new AdminGUI(userInfo).setVisible(true);
                                break;
                        }
                        this.dispose(); // 로그인 창 닫기
                    });
                } else {
                    // --- 서버 비즈니스 로직 상 실패  ---
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, response.getMessage(), "로그인 실패", JOptionPane.WARNING_MESSAGE);
                        resetFieldsForFailure();
                    });
                }
            }, 
            (String errorMessage) -> {
                // --- 네트워크 통신 자체가 실패했을 때 ---
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, errorMessage, "네트워크 오류", JOptionPane.ERROR_MESSAGE);
                });
            }
        );
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            // 현재 실행 중인 OS의 시스템 테마를 가져와 설정합니다.
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, "시스템 테마를 설정할 수 없습니다.", ex);
        }

        /* GUI 쓰레드(Event Dispatch Thread)에서 창 생성 및 표시 */
        java.awt.EventQueue.invokeLater(() -> {
            LoginGUI loginFrame = new LoginGUI();
            
            // 실시간 시계 작동 시작 (1초마다 업데이트)
            // jLabelTime의 텍스트를 매초 갱신
            new javax.swing.Timer(1000, e -> {
                loginFrame.jLabelTime.setText(loginFrame.getTime());
            }).start();
            
            // 창을 화면에 표시
            loginFrame.setVisible(true);
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRole;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButtonAdm;
    private javax.swing.JRadioButton jRadioButtonAss;
    private javax.swing.JRadioButton jRadioButtonPro;
    private javax.swing.JRadioButton jRadioButtonStu;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
