/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Reservation;

import com.crsystem.common.dto.ReservationDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.systemclient.controller.ReservationController;
import com.crsystem.systemclient.controller.SessionManager;
import com.crsystem.common.dto.UserDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author wonsik
 */
public class ReservationRegisterGUI extends javax.swing.JPanel {

    private java.time.LocalDate selectedDate;
    private String day;
    private String periodInfo;
    private int duration;
    private String roomName;

    public ReservationRegisterGUI(String roomName, java.time.LocalDate selectedDate, String periodInfo, int duration) {
        this.roomName = roomName;
        this.selectedDate = selectedDate;
        this.periodInfo = periodInfo;
        this.duration = duration;

        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        this.day = dayNames[selectedDate.getDayOfWeek().getValue()];

        initComponents();
        customInit();
    }

    private void customInit() {
        lblInfo.setText("[" + roomName + "] " + selectedDate + " (" + day + "요일) / " + periodInfo);
        updateCapacityLabel();
    }

    @SuppressWarnings("unchecked")
    private void updateCapacityLabel() {
        com.crsystem.systemclient.controller.TimetableController.getInstance().getTimetable("2026",
            response -> {
                if (!response.isSuccess() || !(response.getPayload() instanceof java.util.Map)) return;

                java.util.Map<String, Object> timetableData = (java.util.Map<String, Object>) response.getPayload();

                java.util.regex.Matcher m = java.util.regex.Pattern
                        .compile("^(.+?)\\s+(\\d+층)\\s+(\\d+호)$")
                        .matcher(roomName);
                if (!m.matches()) return;

                String building = m.group(1);
                String floor    = m.group(2);
                String roomKey  = m.group(3);

                int capacity = 0;
                outer:
                for (Object semObj : timetableData.values()) {
                    if (!(semObj instanceof java.util.Map)) continue;
                    java.util.Map<String, Object> semMap = (java.util.Map<String, Object>) semObj;
                    java.util.Map<String, Object> bMap = (java.util.Map<String, Object>) semMap.get(building);
                    if (bMap == null) continue;
                    java.util.Map<String, Object> fMap = (java.util.Map<String, Object>) bMap.get(floor);
                    if (fMap == null) continue;
                    java.util.Map<String, Object> rData = (java.util.Map<String, Object>) fMap.get(roomKey);
                    if (rData == null) continue;
                    java.util.Map<String, Object> info = (java.util.Map<String, Object>) rData.get("info");
                    if (info != null && info.get("capacity") instanceof Integer) {
                        capacity = (Integer) info.get("capacity");
                    }
                    break outer;
                }

                if (capacity <= 0) return;

                int maxAllowed = capacity / 2;
                int occupied = ReservationController.getInstance().getReservationCache().stream()
                        .filter(r -> roomName.equals(r.getRoomName())
                                && selectedDate.equals(r.getDate())
                                && r.getPeriodInfo() != null
                                && java.util.Arrays.stream(periodInfo.split(","))
                                        .anyMatch(p -> r.getPeriodInfo().contains(p.trim()))
                                && r.getStatus() != com.crsystem.common.dto.ReservationDTO.Status.REJECTED)
                        .mapToInt(com.crsystem.common.dto.ReservationDTO.Response::getPartnerCount)
                        .sum();

                int remaining = Math.max(0, maxAllowed - occupied);
                lblCapacity.setText("잔여석 : " + remaining + " / " + maxAllowed + "석 (최대 수용 " + capacity + "명의 50%)");
                lblCapacity.setForeground(remaining <= 5
                        ? new java.awt.Color(200, 0, 0)
                        : new java.awt.Color(0, 120, 0));
            },
            error -> lblCapacity.setText("잔여석 조회 실패")
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        purposeField = new javax.swing.JTextField();
        partnerSpinner = new javax.swing.JSpinner();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        lblInfo.setText("jLabel1");

        purposeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        purposeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeFieldActionPerformed(evt);
            }
        });

        btnSubmit.setText("예약 등록");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("사용 목적 : ");

        jLabel5.setText("동반 인원 수 :");

        lblCapacity.setText("잔여석 : -");
        lblCapacity.setForeground(new java.awt.Color(0, 120, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(partnerSpinner)
                    .addComponent(purposeField, 0, 201, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblCapacity)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(purposeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purposeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeFieldActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        UserDTO.Response user = SessionManager.getInstance().getCurrentUser();

        if (user == null) {
            JOptionPane.showMessageDialog(this, "로그인 정보가 없습니다. 다시 로그인해주세요.");
            return;
        }

        ReservationDTO.Response reservation = new ReservationDTO.Response();
        reservation.setReservationId("RES-" + System.currentTimeMillis());
        reservation.setUserId(user.getId());
        reservation.setUserName(user.getName());
        reservation.setRoleType(user.getRole());
        reservation.setRoomName(this.roomName);
        reservation.setDate(selectedDate);
        reservation.setDay(this.day);
        reservation.setPeriodInfo(this.periodInfo);
        reservation.setPurpose(purposeField.getText());
        reservation.setPartnerCount((int) partnerSpinner.getValue());
        reservation.setStatus(user.getRole() == com.crsystem.common.enums.Role.PROFESSOR
            ? ReservationDTO.Status.APPROVED
            : ReservationDTO.Status.PENDING);

        btnSubmit.setEnabled(false);
        ReservationController.getInstance().addReservation(
            reservation,
            response -> handleCreateReservationResponse(response),
            error -> {
                btnSubmit.setEnabled(true);
                JOptionPane.showMessageDialog(this, error);
            }
        );
    }//GEN-LAST:event_btnSubmitActionPerformed


    private void handleCreateReservationResponse(ResponseDTO response) {
        btnSubmit.setEnabled(true);

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        ReservationController.getInstance().getReservationList(
                "ALL",
                listResponse -> {
                    ReservationController.getInstance().updateCache(listResponse.getPayload());
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                },
                error -> {
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JSpinner partnerSpinner;
    private javax.swing.JTextField purposeField;
    // End of variables declaration//GEN-END:variables
}
