/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Reservation;

import com.crsystem.common.dto.ReservationDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.systemclient.controller.ReservationController;
import com.crsystem.systemclient.controller.SessionManager;
import com.crsystem.common.dto.UserDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author wonsik
 */
public class ReservationRegisterGUI extends javax.swing.JPanel {

    private java.util.List<java.time.LocalDate> dateValues = new java.util.ArrayList<>();
    private String day;
    private String periodInfo;
    private int duration;
    private String roomName;

    public ReservationRegisterGUI(String roomName, String day, String periodInfo, int duration) {
        this.roomName = roomName;
        this.day = day;
        this.periodInfo = periodInfo;
        this.duration = duration;
        initComponents();
        customInit();
    }

    private void customInit() {
        lblInfo.setText("[" + roomName + "] " + day + "요일 / " + periodInfo);

        java.time.LocalDate today = java.time.LocalDate.now();
        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();

        for (int i = 2; i <= 14; i++) {
            java.time.LocalDate d = today.plusDays(i);
            String label = d.toString() + " (" + dayNames[d.getDayOfWeek().getValue()] + ")";
            model.addElement(label);
            dateValues.add(d);
        }

        dateCombo.setModel(model);
        dateCombo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox<>();
        purposeField = new javax.swing.JTextField();
        partnerSpinner = new javax.swing.JSpinner();
        btnList = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        lblInfo.setText("jLabel1");

        jLabel2.setText("날짜 선택 :");

        dateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        purposeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        purposeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeFieldActionPerformed(evt);
            }
        });

        btnList.setText("예약 목록 확인");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnSubmit.setText("예약 등록");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("사용 목적 : ");

        jLabel5.setText("동반 인원 수 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(partnerSpinner)
                        .addComponent(purposeField)
                        .addComponent(dateCombo, 0, 201, Short.MAX_VALUE))
                    .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(purposeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(partnerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purposeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeFieldActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
    }//GEN-LAST:event_btnListActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        java.time.LocalDate selectedDate = dateValues.get(dateCombo.getSelectedIndex());
        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        String actualDay = dayNames[selectedDate.getDayOfWeek().getValue()];

        // 1. 요일 매칭 검증 (시간표 요일과 선택 날짜 요일 대조)
        if (!actualDay.equals(this.day)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "선택하신 날짜는 " + actualDay + "요일입니다.\n시간표에서 선택한 " + this.day + "요일과 일치해야 합니다.");
            return;
        }

        UserDTO.Response user = SessionManager.getInstance().getCurrentUser();

        if (user == null) {
            JOptionPane.showMessageDialog(this, "로그인 정보가 없습니다. 다시 로그인해주세요.");
            return;
        }

        ReservationDTO.Response reservation = new ReservationDTO.Response();
        reservation.setReservationId("RES-" + System.currentTimeMillis());
        reservation.setUserId(user.getId());
        reservation.setUserName(user.getName());
        reservation.setRoleType(user.getRole());
        reservation.setRoomName(this.roomName);
        reservation.setDate(selectedDate);
        reservation.setDay(this.day);
        reservation.setPeriodInfo(this.periodInfo);
        reservation.setPurpose(purposeField.getText());
        reservation.setPartnerCount((int) partnerSpinner.getValue());
        reservation.setStatus(user.getRole() == com.crsystem.common.enums.Role.PROFESSOR
            ? ReservationDTO.Status.APPROVED
            : ReservationDTO.Status.PENDING);

        btnSubmit.setEnabled(false);
        ReservationController.getInstance().addReservation(
            reservation,
            response -> handleCreateReservationResponse(response),
            error -> {
                btnSubmit.setEnabled(true);
                JOptionPane.showMessageDialog(this, error);
            }
        );
    }//GEN-LAST:event_btnSubmitActionPerformed


    private void handleCreateReservationResponse(ResponseDTO response) {
        btnSubmit.setEnabled(true);

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        ReservationController.getInstance().getReservationList(
                "ALL",
                listResponse -> {
                    ReservationController.getInstance().updateCache(listResponse.getPayload());
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                },
                error -> {
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JSpinner partnerSpinner;
    private javax.swing.JTextField purposeField;
    // End of variables declaration//GEN-END:variables
}
