/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Reservation;

import com.crsystem.common.dto.ReservationDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.systemclient.controller.ReservationController;
import com.crsystem.systemclient.controller.SessionManager;
import com.crsystem.common.dto.UserDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author wonsik
 */
public class ReservationRegisterGUI extends javax.swing.JPanel {

    private java.time.LocalDate selectedDate;
    private String day;
    private String periodInfo;
    private int duration;
    private String roomName;

    public ReservationRegisterGUI(String roomName, java.time.LocalDate selectedDate, String periodInfo, int duration) {
        this.roomName = roomName;
        this.selectedDate = selectedDate;
        this.periodInfo = periodInfo;
        this.duration = duration;

        String[] dayNames = {"", "월", "화", "수", "목", "금", "토", "일"};
        this.day = dayNames[selectedDate.getDayOfWeek().getValue()];

        initComponents();
        customInit();
    }

    private void customInit() {
        lblInfo.setText("[" + roomName + "] " + selectedDate + " (" + day + "요일) / " + periodInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        purposeField = new javax.swing.JTextField();
        partnerSpinner = new javax.swing.JSpinner();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        lblInfo.setText("jLabel1");

        purposeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        purposeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeFieldActionPerformed(evt);
            }
        });

        btnSubmit.setText("예약 등록");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("사용 목적 : ");

        jLabel5.setText("동반 인원 수 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(partnerSpinner)
                    .addComponent(purposeField, 0, 201, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(purposeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purposeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeFieldActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        UserDTO.Response user = SessionManager.getInstance().getCurrentUser();

        if (user == null) {
            JOptionPane.showMessageDialog(this, "로그인 정보가 없습니다. 다시 로그인해주세요.");
            return;
        }

        ReservationDTO.Response reservation = new ReservationDTO.Response();
        reservation.setReservationId("RES-" + System.currentTimeMillis());
        reservation.setUserId(user.getId());
        reservation.setUserName(user.getName());
        reservation.setRoleType(user.getRole());
        reservation.setRoomName(this.roomName);
        reservation.setDate(selectedDate);
        reservation.setDay(this.day);
        reservation.setPeriodInfo(this.periodInfo);
        reservation.setPurpose(purposeField.getText());
        reservation.setPartnerCount((int) partnerSpinner.getValue());
        reservation.setStatus(user.getRole() == com.crsystem.common.enums.Role.PROFESSOR
            ? ReservationDTO.Status.APPROVED
            : ReservationDTO.Status.PENDING);

        btnSubmit.setEnabled(false);
        ReservationController.getInstance().addReservation(
            reservation,
            response -> handleCreateReservationResponse(response),
            error -> {
                btnSubmit.setEnabled(true);
                JOptionPane.showMessageDialog(this, error);
            }
        );
    }//GEN-LAST:event_btnSubmitActionPerformed


    private void handleCreateReservationResponse(ResponseDTO response) {
        btnSubmit.setEnabled(true);

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        ReservationController.getInstance().getReservationList(
                "ALL",
                listResponse -> {
                    ReservationController.getInstance().updateCache(listResponse.getPayload());
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                },
                error -> {
                    JOptionPane.showMessageDialog(this, response.getMessage());
                    javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (f != null) f.dispose();
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JSpinner partnerSpinner;
    private javax.swing.JTextField purposeField;
    // End of variables declaration//GEN-END:variables
}
