/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Reservation;

import com.crsystem.common.dto.ReservationDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.systemclient.controller.ReservationController;
import com.crsystem.systemclient.controller.SessionManager;
import java.util.List;
/**
 *
 * @author wonsik
 */
public class RoomListGUI extends javax.swing.JPanel {

    /**
     * Creates new form RoomListGUI
     */
    public RoomListGUI() {
        initComponents();
        initCustomSettings();
        loadReservationsFromServer();
    }

    private void initCustomSettings() {
        // 시계
        jLabelTime.setText(getCurrentTime());
        new javax.swing.Timer(1000, e -> jLabelTime.setText(getCurrentTime())).start();

        // 로그아웃 버튼
        jButtonLogout.addActionListener(e -> handleLogout());

        // 컬럼 클릭으로 정렬
        jTable1.setAutoCreateRowSorter(true);
        jTable2.setAutoCreateRowSorter(true);
    }

    private String getCurrentTime() {
        return java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd  HH:mm:ss"));
    }

    private void handleLogout() {
        SessionManager.getInstance().logout();

        // 현재 부모 JFrame 닫기
        javax.swing.JFrame parentFrame =
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) parentFrame.dispose();

        // 로그인 화면으로 이동
        javax.swing.SwingUtilities.invokeLater(() ->
                new com.crsystem.systemclient.view.LoginGUI().setVisible(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelClassRoomListTitle = new javax.swing.JLabel();
        jPanelCondition = new javax.swing.JPanel();
        jLabelYear = new javax.swing.JLabel();
        jLabelBuildingNo = new javax.swing.JLabel();
        jLabelSemester = new javax.swing.JLabel();
        jLabelClassRoom = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jComboBoxBuildingNo = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabelFloor = new javax.swing.JLabel();
        jComboBoxFloor = new javax.swing.JComboBox<>();
        jLabelTime = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneScheduleList = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPaneReservationList = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnGoToReserve = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(850, 500));

        jLabelClassRoomListTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabelClassRoomListTitle.setText("Class-Room List");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClassRoomListTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelClassRoomListTitle)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabelYear.setText("년도");

        jLabelBuildingNo.setText("건물");

        jLabelSemester.setText("학기");

        jLabelClassRoom.setText("강의실");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024", "2023" }));

        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1학기", "2학기" }));

        jComboBoxBuildingNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "건물선택", "23 정보공학관", "20 산학협력관" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "강의실 선택", "911", "912", "913", "914", "915", "916", "918" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabelFloor.setText("층");

        jComboBoxFloor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "층 선택", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanelConditionLayout = new javax.swing.GroupLayout(jPanelCondition);
        jPanelCondition.setLayout(jPanelConditionLayout);
        jPanelConditionLayout.setHorizontalGroup(
            jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConditionLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelConditionLayout.createSequentialGroup()
                        .addComponent(jLabelYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286)
                        .addComponent(jLabelSemester))
                    .addGroup(jPanelConditionLayout.createSequentialGroup()
                        .addComponent(jLabelBuildingNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBuildingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabelFloor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelClassRoom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanelConditionLayout.setVerticalGroup(
            jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConditionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYear)
                    .addComponent(jLabelSemester)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClassRoom)
                        .addComponent(jComboBoxBuildingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFloor)
                        .addComponent(jComboBoxFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBuildingNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTime.setText("Current Time");

        jButtonLogout.setText("LogOut");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneScheduleList.setViewportView(jTable1);

        jTabbedPane1.addTab("강의실 시간표", jScrollPaneScheduleList);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneReservationList.setViewportView(jTable2);

        jTabbedPane1.addTab("예약 현황", jScrollPaneReservationList);

        btnGoToReserve.setText("선택한 강의실 예약하기");
        btnGoToReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToReserveActionPerformed(evt);
            }
        });

        btnRefresh.setText("새로고침");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanelCondition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGoToReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jLabelTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTime)
                    .addComponent(jButtonLogout)
                    .addComponent(btnGoToReserve)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToReserveActionPerformed
        // TODO add your handling code here:
        String building = (String) jComboBoxBuildingNo.getSelectedItem();
        String floor = (String) jComboBoxFloor.getSelectedItem();
        String room = (String) jComboBox4.getSelectedItem();

        if ("건물선택".equals(building) || "층 선택".equals(floor) || "강의실 선택".equals(room)) {
            javax.swing.JOptionPane.showMessageDialog(this, "건물, 층, 강의실을 모두 선택해주세요.");
            return;
        }

        if (!"23 정보공학관".equals(building) || !"9".equals(floor)
                || !("911".equals(room) || "912".equals(room) || "913".equals(room))) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "선택하신 강의실은 현재 준비 중입니다.\n(현재는 '23 정보공학관' - '9층' - '911, 912, 913호'만 예약 가능합니다.)");
            return;
        }

        // 어떤 강의실인지 명칭 결합 ("23 정보공학관 9층 912호")
        String roomName = building + " " + floor + "층 " + room + "호";

        CRSystemTimetableUI timetableFrame = new CRSystemTimetableUI(roomName);

        timetableFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // 사용자가 예약 처리를 마친 후 창을 닫으면, 메인 화면의 테이블을 즉시 새로고침
                updateReservationTable();
            }
        });
        timetableFrame.setVisible(true);
    }//GEN-LAST:event_btnGoToReserveActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        // 강의실 선택이 변경될 때마다 해당 강의실 전용 예약 정보로 표를 갱신합니다.
        updateReservationTable();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadReservationsFromServer();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // ==========================================
    // 서버에서 전체 예약 목록 조회 후 테이블 갱신
    // ==========================================
    private void loadReservationsFromServer() {
        ReservationController.getInstance().getReservationList(
            "ALL",
            (ResponseDTO response) -> {
                if (response.isSuccess()) {
                    ReservationController.getInstance().updateCache(response.getPayload());
                    updateReservationTable();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "예약 현황 조회 실패: " + response.getMessage());
                }
            },
            error -> javax.swing.JOptionPane.showMessageDialog(this, "통신 오류: " + error)
        );
    }

    // ==========================================
    // 조회된 데이터로 예약 현황 테이블 렌더링
    // ==========================================
    public void updateReservationTable() {
        String building = (String) jComboBoxBuildingNo.getSelectedItem();
        String floor    = (String) jComboBoxFloor.getSelectedItem();
        String room     = (String) jComboBox4.getSelectedItem();

        String[] columnNames = {"예약 날짜", "요일", "선택 교시", "예약자", "구분", "사용 목적", "동반 인원", "승인 상태"};
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(columnNames, 0);

        // 강의실이 선택되지 않으면 빈 테이블
        if ("건물선택".equals(building) || "층 선택".equals(floor) || "강의실 선택".equals(room)) {
            jTable2.setModel(model);
            return;
        }

        String targetRoomName = building + " " + floor + "층 " + room + "호";

        List<ReservationDTO.Response> cache = ReservationController.getInstance().getReservationCache();
        if (cache != null) {
            for (ReservationDTO.Response info : cache) {
                if (targetRoomName.equals(info.getRoomName())) {
                    model.addRow(new Object[]{
                        info.getDate() != null ? info.getDate().toString() : "",
                        info.getDay() != null ? info.getDay() + "요일" : "",
                        info.getPeriodInfo(),
                        info.getUserName(),
                        info.getRoleType(),
                        info.getPurpose(),
                        info.getPartnerCount() + "명",
                        info.getStatus()
                    });
                }
            }
        }

        jTable2.setModel(model);
        jTable2.setRowHeight(25);
    }

    public static void main(String args[]) { //테스트용 Jframe 생성용 메인 코드라 삭제해도 됩니다.
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(RoomListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("RoomListGUI 테스트 창");
            frame.setContentPane(new RoomListGUI());
            frame.pack();
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToReserve;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBoxBuildingNo;
    private javax.swing.JComboBox<String> jComboBoxFloor;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabelBuildingNo;
    private javax.swing.JLabel jLabelClassRoom;
    private javax.swing.JLabel jLabelClassRoomListTitle;
    private javax.swing.JLabel jLabelFloor;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelCondition;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPaneReservationList;
    private javax.swing.JScrollPane jScrollPaneScheduleList;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
