/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Reservation;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import com.crsystem.common.dto.ReservationDTO;
import com.crsystem.common.enums.Role;
import com.crsystem.common.dto.UserDTO;
import com.crsystem.systemclient.controller.ReservationController;
import com.crsystem.systemclient.controller.SessionManager;

/**
 *
 * @author wonsik
 */
public class TimeTableGUI extends javax.swing.JPanel {

    private List<Point> selectedCells = new ArrayList<>();
    private String[] days = {"월", "화", "수", "목", "금"};
    private String roomName;

    public TimeTableGUI(String roomName) {
        this.roomName = roomName;
        initComponents();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(9);

        String[] times = {"1교시(09:00)", "2교시(10:00)", "3교시(11:00)", "4교시(12:00)",
            "5교시(13:00)", "6교시(14:00)", "7교시(15:00)", "8교시(16:00)", "9교시(17:00)"};
        for (int i = 0; i < 9; i++) {
            model.setValueAt(times[i], i, 0);
        }

        table.setRowHeight(45);
        table.setCellSelectionEnabled(true);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        table.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(Color.WHITE);

                String day = column > 0 ? days[column - 1] : null;
                String period = (row + 1) + "교시";

                for (ReservationDTO.Response reservation : ReservationController.getInstance().getReservationCache()) {
                    if (reservation.getRoomName().equals(roomName)
                            && reservation.getDay().equals(day)
                            && reservation.getPeriodInfo().contains(period)) {
                        if (reservation.getRoleType() == Role.STUDENT) {
                            c.setBackground(new Color(180, 255, 180));
                        } else if (reservation.getRoleType() == Role.PROFESSOR) {
                            c.setBackground(new Color(255, 200, 220));
                        }
                    }
                }

                for (Point p : selectedCells) {
                    if (p.x == row && p.y == column) {
                        c.setBackground(new Color(180, 200, 255));
                    }
                }
                return c;
            }
        });

        refreshReservationCache();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnReserve = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "교시/요일", "월", "화", "수", "목", "금"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnReserve.setText("선택한 교시 예약 신청하기");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addComponent(btnReserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserve)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        int col = table.getSelectedColumn();

        if (row < 0 || col <= 0) {
            return;
        }

        String selectedDay = days[col - 1];
        String selectedPeriod = (row + 1) + "교시";

        UserDTO.Response currentUser
        = SessionManager.getInstance().getCurrentUser();

        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "로그인 정보가 없습니다. 다시 로그인해주세요.");
            return;
        }

        for (ReservationDTO.Response reservation
            : ReservationController.getInstance().getReservationCache()) {

            boolean sameRoom
            = reservation.getRoomName()
            .equals(this.roomName);

            boolean sameDay
            = reservation.getDay()
            .equals(selectedDay);

            boolean samePeriod
            = reservation.getPeriodInfo()
            .contains(selectedPeriod);

            if (sameRoom && sameDay && samePeriod) {
                // 학생 차단

                if (currentUser.getRole() == Role.STUDENT) {
                    JOptionPane.showMessageDialog(
                        this,
                        "이미 예약된 교시입니다."
                    );

                    return;
                }

                // 교수 -> 교수 예약 시도
                if (currentUser.getRole() == Role.PROFESSOR
                    && reservation.getRoleType() == Role.PROFESSOR) {
                    JOptionPane.showMessageDialog(
                        this,
                        "이미 교수 예약이 존재합니다."
                    );
                    return;
                }

                // 교수 -> 학생 예약 시도
                if (currentUser.getRole() == Role.PROFESSOR
                    && reservation.getRoleType() == Role.STUDENT) {
                    break;
                }
            }
        }

        Point p = new Point(row, col);

        if (selectedCells.contains(p)) {
            selectedCells.remove(p);
        } else {
            selectedCells.add(p);
        }

        table.repaint();
    }//GEN-LAST:event_tableMouseClicked

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
        if (selectedCells.isEmpty()) {
            JOptionPane.showMessageDialog(this, "예약할 교시를 선택해주세요.");
            return;
        }
        List<Integer> rows = new ArrayList<>();
        int col = selectedCells.get(0).y;
        for (Point p : selectedCells) {
            if (p.y != col) {
                JOptionPane.showMessageDialog(this, "같은 요일 내에서만 선택 가능합니다.");
                return;
            }
            rows.add(p.x);
        }
        Collections.sort(rows);
        for (int i = 0; i < rows.size() - 1; i++) {
            if (rows.get(i + 1) != rows.get(i) + 1) {
                JOptionPane.showMessageDialog(this, "연속된 교시만 예약 가능합니다.");
                return;
            }
        }

        UserDTO.Response currentUser
        = SessionManager.getInstance().getCurrentUser();

        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "로그인 정보가 없습니다. 다시 로그인해주세요.");
            return;
        }

        if (currentUser.getRole() == Role.STUDENT
            && rows.size() > 2) {
            JOptionPane.showMessageDialog(
                this,
                "학생은 최대 2교시까지만 예약 가능합니다."
            );
            return;
        }

        if (currentUser.getRole() == Role.PROFESSOR
            && rows.size() > 3) {
            JOptionPane.showMessageDialog(
                this,
                "교수는 최대 3교시까지만 예약 가능합니다."
            );
            return;
        }

        String periodString = rows.stream().map(r -> (r + 1) + "교시").collect(java.util.stream.Collectors.joining(", "));

        // 상세 예약창 호출
        ReservationRegisterGUI reservationPanel = new ReservationRegisterGUI(this.roomName, days[col - 1], periodString, rows.size());
        javax.swing.JFrame reservationFrame = new javax.swing.JFrame("강의실 예약 등록");
        reservationFrame.setContentPane(reservationPanel);
        reservationFrame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        reservationFrame.pack();
        reservationFrame.setLocationRelativeTo(javax.swing.SwingUtilities.getWindowAncestor(this));
        reservationFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                refreshReservationCache();
            }
        });
        reservationFrame.setVisible(true);
        selectedCells.clear();
        table.repaint();
    }//GEN-LAST:event_btnReserveActionPerformed


    private void refreshReservationCache() {
        ReservationController.getInstance().getReservationList(
                "ALL",
                response -> {
                    if (response.isSuccess()) {
                        ReservationController.getInstance().updateCache(response.getPayload());
                        table.repaint();
                    }
                },
                error -> System.err.println("[TimeTableGUI] 예약 목록 조회 실패: " + error)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserve;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
