/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.crsystem.systemclient.view.Admin;

import com.crsystem.common.dto.RequestDTO;
import com.crsystem.common.dto.ResponseDTO;
import com.crsystem.common.dto.UserDTO;
import com.crsystem.common.enums.Role;
import com.crsystem.systemclient.main.CRSystemClient;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.Window;

/**
 * 사용자 추가 
 * @author wonsik
 */
public class AddUserGUI extends javax.swing.JPanel {
    
    private ButtonGroup roleGroup; // 라디오 버튼을 하나로 묶어줄 그룹
    
    /**
     * Creates new form AddUserGUI
     */
    public AddUserGUI() {
        initComponents();
        initCustomSettings(); // 커스텀 세팅 추가
    }
    
    private void initCustomSettings() {
        // 라디오 버튼 그룹화 (중복 선택 방지)
        roleGroup = new ButtonGroup();
        roleGroup.add(jRadioButtonAss); // 조교
        roleGroup.add(jRadioButtonPro); // 교수
        roleGroup.add(jRadioButtonStu); // 학생

        // 서버로 보낼 때 쓸 식별자(ActionCommand) 심기
        jRadioButtonAss.setActionCommand(Role.ASSISTANT.name());
        jRadioButtonPro.setActionCommand(Role.PROFESSOR.name());
        jRadioButtonStu.setActionCommand(Role.STUDENT.name());

        // 텍스트 필드 안내 문구 지우기
        jTextFieldName.setText(""); 
        jTextFieldId.setText("");

        // 버튼 클릭 이벤트 연결
        jButtonAdd.addActionListener(evt -> performAddUser());
        jButtonCancel.addActionListener(evt -> performCancel());
    }
    
    private void performAddUser() {
        String name = jTextFieldName.getText().trim();
        String id = jTextFieldId.getText().trim();

        // 입력값 검증
        if (name.isEmpty() || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "이름과 ID를 모두 입력해주세요.");
            return;
        }
        if (roleGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "권한을 선택해주세요.");
            return;
        }

        // 데이터 포장
        String selectedRoleStr = roleGroup.getSelection().getActionCommand();
        Role selectedRole = Role.valueOf(selectedRoleStr);

        UserDTO.Request addPayload = new UserDTO.Request();
        addPayload.setName(name);
        addPayload.setId(id);
        addPayload.setRole(selectedRole);
        addPayload.setPw(id); // 초기 비밀번호는 ID와 동일하게 설정

        RequestDTO envelope = new RequestDTO("ADD_USER", addPayload);

        // 비동기 서버 통신
        CRSystemClient.getInstance().sendRequest(envelope, 
            (ResponseDTO response) -> {
                SwingUtilities.invokeLater(() -> {
                    if (response.isSuccess()) {
                        JOptionPane.showMessageDialog(this, "사용자 추가가 완료되었습니다!\n(초기 비밀번호는 ID와 동일합니다.)");
                        performCancel(); // 성공하면 창 닫기
                    } else {
                        JOptionPane.showMessageDialog(this, response.getMessage(), "추가 실패", JOptionPane.WARNING_MESSAGE);
                    }
                });
            }, 
            (String errorMessage) -> {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "통신 오류: " + errorMessage, "에러", JOptionPane.ERROR_MESSAGE);
                });
            }
        );
    }
    
    private void performCancel() {
        // 원래 패널 지우기 
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabelRole = new javax.swing.JLabel();
        jRadioButtonAss = new javax.swing.JRadioButton();
        jRadioButtonPro = new javax.swing.JRadioButton();
        jRadioButtonStu = new javax.swing.JRadioButton();
        jLabelName = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabelTitle.setText("사용자 추가");

        jButtonCancel.setText("취소");

        jButtonAdd.setText("추가");

        jLabelRole.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabelRole.setText("권한");

        jRadioButtonAss.setText("조교");

        jRadioButtonPro.setText("교수");

        jRadioButtonStu.setText("학생");

        jLabelName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabelName.setText("이름");

        jLabelId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabelId.setText("ID");

        jTextFieldName.setText("이름");

        jTextFieldId.setText("교원번호, 학번");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonAss)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonStu))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldId)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRole)
                    .addComponent(jRadioButtonAss)
                    .addComponent(jRadioButtonPro)
                    .addComponent(jRadioButtonStu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAdd))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JRadioButton jRadioButtonAss;
    private javax.swing.JRadioButton jRadioButtonPro;
    private javax.swing.JRadioButton jRadioButtonStu;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
